covid_19/accounts/urls.py
from django.urls import path ,reverse_lazy
from . import views
from django.conf.urls.static import static  
from django.contrib.auth.views import LogoutView
from .views import Sign_Up,Login
from django.conf import settings

app_name = 'accounts'

urlpatterns = [
    path('signup/',views.Sign_Up, name='signup'),
    path('Loggin_in/', views.Loggin_in, name='Loggin_in'),
    path('login/', views.Login, name='login'),
    path('logout/',LogoutView.as_view(next_page = reverse_lazy('accounts:login')) ,  name="logout"),
    #path('Profile/', views.Profile ,name= 'Profile' ),
    path('dashboard/', views.dashboard ,name= 'dashboard' ),
  
 
]
urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

covid_19/covid_19/urls.py
from django.contrib import admin
from django.urls import path ,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('' , include('home.urls' ), name='home'),
    path('' , include('accounts.urls') , name='accounts'),
    path('' , include('test_img.urls') , name='test_img'),
]
urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

covid_19/home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
   
    path('', views.home, name='home'),
   # path('', views.Home.as_view() ,name='home'),
]

covid_19/accounts/models.py
from django.db import models
from django.contrib.auth.models import PermissionsMixin
from django.contrib.auth.base_user import AbstractBaseUser
from .manager import UserManager

class User(AbstractBaseUser, PermissionsMixin):
	SICKNES = (
		('Asthma' , 'Asthma') , 
		('Lung Cancer' , 'Lung Cancer') , 
		('Heart disease' , 'Heart disease') , 
		('Tuberculosis' , 'Tuberculosis') , 
		('diabetic' , 'diabetic') , 
		('Blood disorders' , 'Blood disorders') , 
		('Cancers' , 'Cancers') , 
		('HIV' , 'HIV') , 
		('Kidney disease' , 'Kidney disease') , )

	GENDER_CHOICES = (
		('Male' , 'Male') ,

		('Female' , 'Female'))

	SMOKE = (
		('Yes' , 'Yes') , 
		('No' , 'No'))

	COUNTRIES = (
		('Albania' , 'Albania'), 
		('Algeria' , 'Algeria'), 
		('American Samoa' , 'American Samoa') , 
		('Andorra' , 'Andorra') , 
		('Angola' , 'Angola') , 
		('Anguilla' , 'Anguilla'), 
		('Antigua & Barbuda' , 'Antigua & Barbuda') , 
		('Argentina' , 'Argentina') , 
		('Armenia' , 'Armenia') , 
		('Aruba' , 'Aruba'), 
		('Australia' , 'Australia') , 
		('Austria' , 'Austria') , 
		('Azerbaijan' , 'Azerbaijan') , 
		('Bahamas' , 'Bahamas'), 
		('Bahrain' , 'Bahrain') , 
		('Bangladesh' , 'Bangladesh') , 
		('Barbados' , 'Barbados') , 
		('Belarus' , 'Belarus'), 
		('Belgium' , 'Belgium') , 
		('Belize' , 'Belize') ,  
		('Benin' , 'Benin') , 
		('Bermuda' , 'Bermuda') , 
		('Bhutan' , 'Bhutan') , 
		('Bolivia' , 'Bolivia') , 
		('Bonaire' , 'Bonaire') , 
		('Bosnia & Herzegovina' , 'Bosnia & Herzegovina'), 
		('Botswana' , 'Botswana') ,
		('Brazil' , 'Brazil') , 
		('British Indian Ocean Ter' , 'British Indian Ocean Ter') , 
		('Brunei' , 'Brunei'), 
		('Bulgaria' , 'Bulgaria') , 
		('Burkina Faso' , 'Burkina Faso') ,
		('Burundi' , 'Burundi') , 
		('Cambodia' , 'Cambodia') , 
		('Cameroon' , 'Cameroon') ,
		('Canada' , 'Canada') , 
		('Canary Islands' , 'Canary Islands') , 
		('Cape Verde' , 'Cape Verde') ,
		('Cayman Islands' , 'Cayman Islands') , 
		('Central African Republic' , 'Central African Republic') ,
		('Chad' , 'Chad') , 
		('Channel Islands' , 'Channel Islands') , 
		('Chile' , 'Chile') ,
		('China' , 'China') , 
		('Christmas Island' , 'Christmas Island') , 
		('Cocos Island' , 'Cocos Island') ,
		('Colombia' , 'Colombia') , 
		('Comoros' , 'Comoros') , 
		('Congo' , 'Congo') , 
		('Cook Islands' , 'Cook Islands') , 
		('Costa Rica' , 'Costa Rica') , 
		('Cote DIvoire' , 'Cote DIvoire') ,
		('Croatia' , 'Croatia') , 
		('Cuba' , 'Cuba') , 
		('Curaco' , 'Curaco') , 
		('Cyprus' , 'Cyprus') , 
		('Czech Republic' , 'Czech Republic') , 
		('Denmark' , 'Denmark') , 
		('Djibouti' , 'Djibouti') , 
		('Dominica' , 'Dominica') , 
		('Dominican Republic' , 'Dominican Republic') , 
		('East Timor' , 'East Timor') , 
		('Ecuador' , 'Ecuador') , 
		('Egypt' , 'Egypt') , 
		('El Salvador' , 'El Salvador') , 
		('Equatorial Guinea' , 'Equatorial Guinea') , 
		('Eritrea' , 'Eritrea') ,
		('Estonia' , 'Estonia') , 
		('Ethiopia' , 'Ethiopia') , 
		('Falkland Islands' , 'Falkland Islands') ,
		('Faroe Islands' , 'Faroe Islands') , 
		('Fiji' , 'Fiji') , 
		('Finland' , 'Finland') ,
		('France' , 'France') , 
		('French Guiana' , 'French Guiana') , 
		('French Polynesia' , 'French Polynesia') ,
		('French Southern Ter' , 'French Southern Ter') , 
		('Gabon' , 'Gabon') , 
		('Gambia' , 'Gambia') , 
		('Georgia' , 'Georgia') , 
		('Germany' , 'Germany') , 
		('Ghana' , 'Ghana') , 
		('Gibraltar' , 'Gibraltar') , 
		('Great Britain' , 'Great Britain') , 
		('Greece' , 'Greece') , 
		('Greenland' , 'Greenland') , 
		('Grenada' , 'Grenada') , 
		('Guadeloupe' , 'Guadeloupe') , 
		('Guam' , 'Guam') , 
		('Guatemala' , 'Guatemala') , 
		('Guinea' , 'Guinea') , 
		('Guyana' , 'Guyana') , 
		('Haiti' , 'Haiti') ,
		('Hawaii' , 'Hawaii') , 
		('Honduras' , 'Honduras') , 
		('Hong Kong' , 'Hong Kong') ,
		('Hungary' , 'Hungary') , 
		('Iceland' , 'Iceland') , 
		('Indonesia' , 'Indonesia') ,
		('India' , 'India') , 
		('Iran' , 'Iran') , 
		('Iraq' , 'Iraq') , 
		('Ireland' , 'Ireland') , 
		('Isle of Man' , 'Isle of Man') , 
		('Israel' , 'Israel') , 
		('Italy' , 'Italy') , 
		('Jamaica' , 'Jamaica') , 
		('Japan' , 'Japan') , 
		('Jordan' , 'Jordan') , 
		('Kazakhstan' , 'Kazakhstan') , 
		('Kenya' , 'Kenya') , 
		('Kiribati' , 'Kiribati') , 
		('Korea North' , 'Korea North') , 
		('Korea Sout' , 'Korea Sout') , 
		('Kuwait' , 'Kuwait') , 
		('Kyrgyzstan' , 'Kyrgyzstan') , 
		('Laos' , 'Laos') ,
		('Latvia' , 'Latvia') , 
		('Lebanon' , 'Lebanon') , 
		('Lesotho' , 'Lesotho') ,
		('Liberia' , 'Liberia') , 
		('Libya' , 'Libya') , 
		('Liechtenstein' , 'Liechtenstein') ,
		('Lithuania' , 'Lithuania') , 
		('Luxembourg' , 'Luxembourg') , 
		('Macau' , 'Macau') ,
		('Macedonia' , 'Macedonia') , 
		('Madagascar' , 'Madagascar') , 
		('Malaysia' , 'Malaysia') ,
		('Malawi' , 'Malawi') , 
		('Maldives' , 'Maldives') , 
		('Mali' , 'Mali') ,
		('Malta' , 'Malta') , 
		('Marshall Islands' , 'Marshall Islands') , 
		('Martinique' , 'Martinique') ,
		('Mauritania' , 'Mauritania') , 
		('Mauritius' , 'Mauritius') , 
		('Mayotte' , 'Mayotte') ,
		('Mexico' , 'Mexico') , 
		('Midway Islands' , 'Midway Islands') , 
		('Moldova' , 'Moldova') ,
		('Monaco' , 'Monaco') , 
		('Mongolia' , 'Mongolia') , 
		('Montserrat' , 'Montserrat') ,
		('Morocco' , 'Morocco') , 
		('Mozambique' , 'Mozambique') , 
		('Myanmar' , 'Myanmar') ,
		('Nambia' , 'Nambia') , 
		('Nauru' , 'Nauru') , 
		('Nepal' , 'Nepal') ,
		('Netherland Antilles' , 'Netherland Antilles') , 
		('Netherlands' , 'Netherlands') , 
		('Nevis' , 'Nevis') , 
		('New Caledonia' , 'New Caledonia') , 
		('New Zealand' , 'New Zealand') , 
		('Nicaragua' , 'Nicaragua') , 
		('Niger' , 'Niger') , 
		('Nigeria' , 'Nigeria') , 
		('Niue' , 'Niue') ,
		('Norfolk Island' , 'Norfolk Island') , 
		('Norway' , 'Norway') , 
		('Oman' , 'Oman') ,
		('Pakistan' , 'Pakistan') , 
		('Palau Island' , 'Palau Island') , 
		('Palestine' , 'Palestine') ,
		('Panama' , 'Panama') , 
		('Papua New Guinea' , 'Papua New Guinea') , 
		('Paraguay' , 'Paraguay') , 
		('Peru' , 'Peru') , 
		('Phillipines' , 'Phillipines') , 
		('Pitcairn Island' , 'Pitcairn Island') , 
		('Poland' , 'Poland') , 
		('Portugal' , 'Portugal') , 
		('Puerto Rico' , 'Puerto Rico') , 
		('Qatar' , 'Qatar') , 
		('Republic of Montenegro' , 'Republic of Montenegro') ,
		('Republic of Serbia' , 'Republic of Serbia') , 
		('Reunion' , 'Reunion') , 
		('Romania' , 'Romania') ,
		('Russia' , 'Russia') , 
		('Rwanda' , 'Rwanda') , 
		('St Barthelemy' , 'St Barthelemy') , 
		('St Eustatius' , 'St Eustatius') , 
		('St Helena' , 'St Helena') , 
		('St Kitts-Nevis' , 'St Kitts-Nevis') , 
		('St Lucia' , 'St Lucia') , 
		('St Maarten' , 'St Maarten') , 
		('St Pierre & Miquelon' , 'St Pierre & Miquelon') , 
		('St Vincent & Grenadines' , 'St Vincent & Grenadines') , 
		('Saipan' , 'Saipan') , 
		('Samoa' , 'Samoa') ,
		('Samoa American' , 'Samoa American') , 
		('San Marino' , 'San Marino') ,
		('Sao Tome & Principe' , 'Sao Tome & Principe') , 
		('Saudi Arabia' , 'Saudi Arabia') ,
		('Senegal' , 'Senegal') , 
		('Seychelles' , 'Seychelles') , 
		('Sierra Leone' , 'Sierra Leone') , 
		('Singapore' , 'Singapore') , 
		('Slovakia' , 'Slovakia') , 
		('Slovenia' , 'Slovenia') , 
		('Solomon Islands' , 'Solomon Islands') , 
		('Somalia' , 'Somalia') , 
		('South Africa' , 'South Africa') ,
		('Spain' , 'Spain') , 
		('Sri Lanka' , 'Sri Lanka') , 
		('Sudan' , 'Sudan') , 
		('Suriname' , 'Suriname') ,
		('Swaziland' , 'Swaziland') , 
		('Sweden' , 'Sweden') , 
		('Switzerland' , 'Switzerland') , 
		('Syria' , 'Syria') , 
		('Tahiti' , 'Tahiti') , 
		('Taiwan' , 'Taiwan') , 
		('Tajikistan' , 'Tajikistan') , 
		('Tanzania' , 'Tanzania') , 
		('Thailand' , 'Thailand') , 
		('Togo' , 'Togo') , 
		('Tokelau' , 'Tokelau') , 
		('Tonga' , 'Tonga') , 
		('Trinidad & Tobago' , 'Trinidad & Tobago') , 
		('Tunisia' , 'Tunisia') , 
		('Turkey' , 'Turkey') , 
		('Turkmenistan' , 'Turkmenistan') , 
		('Turks & Caicos Is' , 'Turks & Caicos Is') , 
		('Tuvalu' , 'Tuvalu') , 
		('Uganda' , 'Uganda') , 
		('United Kingdom' , 'United Kingdom') ,
		('Ukraine' , 'Ukraine') , 
		('United Arab Erimates' , 'United Arab Erimates') , 
		('United States of America' , 'United States of America') , 
		('Uraguay' , 'Uraguay') ,
		('Uzbekistan' , 'Uzbekistan') , 
		('Vanuatu' , 'Vanuatu') , 
		('Vatican City State' , 'Vatican City State') ,
		('Venezuela' , 'Venezuela') , 
		('Vietnam' , 'Vietnam') , 
		('Virgin Islands (Brit)' , 'Virgin Islands (Brit)') , 
		('Virgin Islands (USA)' , 'Virgin Islands (USA)') , 
		('Wake Island' , 'Wake Island') , 
		('Wallis & Futana Is' , 'Wallis & Futana Is') , 
		('Yemen' , 'Yemen') ,
		('Zaire' , 'Zaire') , 
		('Zambia' , 'Zambia') , 
		('Zimbabwe' , 'Zimbabwe') ,
	
	)
	


	
	email = models.EmailField(('email address'), unique=True)
	first_name = models.CharField(('first name'), max_length=25, null=True)
	last_name = models.CharField(('last name'), max_length=25, null=True)
	date_joined = models.DateTimeField(('date joined'), auto_now_add = True, blank=True, null=True)
	is_active = models.BooleanField(('active'), default=True)
	is_superuser = models.BooleanField(('superuser'), default=False)
	is_admin = models.BooleanField(('admin'), default=False)
	is_staff = models.BooleanField(('staff'), default=False)
	Phone_Number = models.CharField(max_length = 200 )
	Age = models.IntegerField(null=True  )
	Country = models.CharField(max_length = 30, choices = COUNTRIES, null=True)
	Sickness = models.CharField(max_length = 30 , choices = SICKNES, null=True)
	Gender = models.CharField(max_length = 30,  choices = GENDER_CHOICES, null=True )
	Smoking = models.CharField(max_length = 30,  choices = SMOKE, null=True )

	objects = UserManager()

	USERNAME_FIELD = 'email'
	REQUIRED_FIELD = []

	class Meta:
		verbose_name = ('user')
		verbose_name_plural = ('user')


	def full_name(self):

		return str("{0} {1}".format(self.first_name, self.last_name)).capitalize()

	def __str__(self):

covid_19/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import User
from .models import *

class regs(UserCreationForm):
	password1 = forms.CharField(label='Password', required=True, widget=forms.PasswordInput)

	password2 = forms.CharField(label='Confirm password', required=True, widget=forms.PasswordInput)


	class Meta:
		model = User 
		fields = ('first_name', 'last_name', 'email', 'password1', 'password2', 
	  'Phone_Number', 'Age', 'Country', 'Sickness', 'Gender', 'Smoking',)

covid_19/accounts/views.py
from django.shortcuts import render, reverse ,redirect, get_object_or_404
from django.http import JsonResponse, HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate, login ,logout
from .models import User
from .forms import regs
from .models import *
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login

 
@login_required
def Profile(request):
    user = get_object_or_404(User, pk=request.user.pk)
    context = {'Profile': user,}
    return render(request, 'profile_user/profile.html', context)


#from profile_user.models import Profiles
# Create your views here.



#def signup(request):
  #  New_User = New_User.objects.create_user(
   #     username = request.POST.get('Reg_UserName_Input'),
   #     password = request.POST.get('Reg_Password_Input'),
   #     email    = request.POST.get('Email_Input'),
   # )
   # New_User.first_name = request.POST.get('FirstName_Input')
   # New_User.last_name = request.POST.get('LastName_Input')
   # New_User.set_password(request.POST.get('Reg_Password_Input'))
    #if you use User.objects.create you must user set_password() method.
    #New_User.set_password(request.POST.get('Password_Input'))
    #New_User.save()
    #return render(request, 'accounts/login.html')
    

            




def Login(requset):
    if requset.user.is_authenticated:
        return render(requset,'home/home.html')
    else:
        return render(requset, 'accounts/login.html')


def Loggin_in(requset):
    if requset.method == 'POST':
        Username = requset.POST.get('Log_UserName_Input')
        Password = requset.POST.get('Log_Password_Input')
        user_auth = authenticate(username=Username, password=Password)
        if user_auth is not None:
            login(requset, user_auth)
            return HttpResponseRedirect(reverse('home:home'))
        else:
            print('User   :', user_auth)
            return render(requset, 'accounts/login.html')

    else:
        return render(requset, 'accounts/login.html')



@login_required
def log_out(request):
	logout(request)
	return redirect('accounts:login')


def Sign_Up(requset):
    data = {}
    if requset.POST:
        print('request')
        form=regs(requset.POST or None)
        data["info"]=form
        if form.is_valid():
           print('valid')
           form.save()
           user = authenticate(email=form.cleaned_data['email'], password=form.cleaned_data['password1'],)
           login(requset,user)
           return render(requset,'home/home.html')
        else:
            print('form not vid')
        return render(requset, 'accounts/signup.html',data)
    
    else:
        print('not valid')
        data["info"] = regs()
        return render(requset, 'accounts/signup.html',data)




@login_required
def dashboard(requset):
    return render(requset, 'accounts/dashboard.html' ) 

covid_19/accounts/templates/accounts/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en"> 
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0"> 
<title>Login</title>
<link rel="preconnect" href="https://fonts.gstatic.com"> 
<link href="https://fonts.googleapis.com/css2?family=Poppins&display=swap" rel="stylesheet">
<link rel="stylesheet" href="{% static 'CSS/style12.css' %}">
</head> 
<body style="background-color: #f8f8f9">

<header class="head"> 
<div class="header">
<div class="logo">
<h1>COVID-19</h1>      
</div> <nav>              
<a href="{% url 'home:home' %}">Home</a>

        <a href="{% url 'accounts:signup' %}">SignUp</a>
        {% if request.user %}
        <a href="{% url 'accounts:login' %} ">LogIn</a>
        {% else %}
        <a href="{% url 'accounts:logout' %} ">LogOut</a>
        {% endif %}
</nav>
    </div> 
        </header>
     <div class="back">
        <div class="container">
            <div class="part">
            <div class="part1"></div>
             <div class="part2">
        <form id="msform" method="POST" action="{% url 'accounts:Loggin_in' %}">
          {% csrf_token %}
            <h2>login</h2>
            <label class="form1" for="Log_UserName_Input">User Name :</label>
            <input  type="text" name="Log_UserName_Input" placeholder="Ahmed_Dr" required >
            <label class="form1" for="Log_Password_Input">Password :</label>
            <input type="password" name="Log_Password_Input" id="myInput" placeholder="Password" required >
            <div class="chekp">
            <input type="checkbox" onclick="myFunction()" class="checkbox1"><p>Show Password </p> </div>
            <input type="submit" value="Login" required>
            <a href="{% url 'accounts:signup' %} ">
            <input type="button" value="SIGN UP" onclick="displaySighnUp()" required>
            </a>
            
            </form>
        </div></div>
    </body>
</html>

covid_19/accounts/templates/accounts/signup.html
{% load static %}
{% block Content %}
<!DOCTYPE html>
<html lang="en"> 
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0"> 
<title>Login</title>
<link rel="preconnect" href="https://fonts.gstatic.com"> 
<link href="https://fonts.googleapis.com/css2?family=Poppins&display=swap" rel="stylesheet">
<link rel="stylesheet" href="{% static 'CSS/style12.css' %}">
</head> 
<body style="background-color: #f8f8f9">

<header class="head"> 
<div class="header">
<div class="logo">
<h1>COVID-19</h1>
</div> <nav> 
<a href="{% url 'home:home' %}">Home</a>

        <a href="{% url 'accounts:signup' %}">SignUp</a>
        {% if request.user %}
            <a href="{% url 'accounts:logout' %} ">LogOut</a>
        {% else %}
            <a href="{% url 'accounts:login' %} ">LogIn</a>
        {% endif %}
</nav>
    </div> 
        </header>
     <div class="back">
        <div class="container">
            <div class="part">
            <div class="part1"></div>
             <div class="part2">
        <form id="msform" method="POST" action="{% url 'accounts:signup' %}">
            {% csrf_token %}
            <h2>SIGN UP</h2>
            {% for field in info %}
            <div>{{field.label}}
              <br>  {{field}}</br>

                    {% for error in field.errors  %}
                <div class="alert alert-danger">
                    <strong>{{ error|escape}}</strong>
                </div>
        {% endfor %}
            </div>
            {% endfor %}
             
    <br>
  
    <hr>
    <br>
                    
             
            <a href="{% url 'accounts:login' %} ">
                <input type="button" value="Login" onclick="displaylogin()" required>
                </a>
                <input type="submit" value="SIGN UP" required ></form>
          </div></div>
    </body>
</html>
{% endblock %}