covid_19/accounts/urls.py
from django.urls import path ,reverse_lazy
from . import views
from django.conf.urls.static import static  
from django.contrib.auth.views import LogoutView
from .views import Sign_Up,Login
from django.conf import settings

app_name = 'accounts'

urlpatterns = [
    path('signup/',views.Sign_Up, name='signup'),
    path('Loggin_in/', views.Loggin_in, name='Loggin_in'),
    path('login/', views.Login, name='login'),
    path('logout/',LogoutView.as_view(next_page = reverse_lazy('accounts:login')) ,  name="logout"),
    #path('Profile/', views.Profile ,name= 'Profile' ),
    path('dashboard/', views.dashboard ,name= 'dashboard' ),
  
 
]
urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

covid_19/covid_19/urls.py
from django.contrib import admin
from django.urls import path ,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('' , include('home.urls' ), name='home'),
    path('' , include('accounts.urls') , name='accounts'),
    path('' , include('test_img.urls') , name='test_img'),
]
urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

covid_19/home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
   
    path('', views.home, name='home'),
   # path('', views.Home.as_view() ,name='home'),
]

covid_19/test_img/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'test_img'

urlpatterns = [
  #  path('test/', views.test_img ,name= 'test_img' ),
    path('total_cases/', views.total_cases ,name= 'total_cases' ),
    path('image_upload/', views.image_upload ,name= 'image_upload' ),
    
 
    
]
urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

covid_19/home/models.py
from django.db import models

# Create your models here.

covid_19/home/views.py
from django.shortcuts import render
from django.views.generic import View , TemplateView


def home(request):
    return render(request, 'home.html')

covid_19/home/templates/home/home.html
{% load static%}

<!DOCTYPE html> 
<html lang="en">
    <head> <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>COVID-19</title>
        <link rel="preconnect" href="https://fonts.gstatic.com"> 
        <link href="https://fonts.googleapis.com/css2?family=Poppins&display=swap" rel="stylesheet"> 
        <link rel="stylesheet" href="{% static 'CSS/style12.css' %}"> 
    </head>
    <body>
        <header class="head">
    <div class="header">
        <div class="logo">
            <h1>COVID-19</h1>
        </div>
        <nav> <a href="{% url 'home:home' %}">Home</a>
          
            <a href="{% url 'accounts:signup' %}">SignUp</a>
            
            {% if request.user %}
                <a href="{% url 'accounts:logout' %} ">LogOut</a>
            {% else %}
                <a href="{% url 'accounts:login' %} ">LogIn</a>
            {% endif %}
        </nav> 
            </div> 
        </header>
    <section id="showcase"> 
        <div class="info">
            <div class="animatediv"> 
  <img src="{% static 'Images/corona-virus.png' %}">
    </div>
            <h1>Ready to test your body ?</h1> 
           <h2> <p>To protect yourself from Coronavirus, follow public health laws and maintain social distancing.</p> </h2>
            <button class="button1"><a href= "{% url 'test_img:image_upload' %}">Test</a></button> 
            <button class="button2">  <a href="{% url 'test_img:total_cases' %}">More info</a> </button>
        </div>
        </section>
        <h1 class="title">Warnings</h1>
        <section id="warning"> <div class="Statey"> 
            <img src="{% static 'Images/report.jpg' %}">
            <h1>statistics</h1> 
            <h2></h2> 
            <h3>from more info</h3> 
            </div> <div class="corona"> 
            <img src="{% static 'Images/covid.jpg' %}">
            <h1>Corona Viros</h1> 
            <h2>spread</h2>
            
            <h3><b>10 milion in the world</b></h3> 
            </div> <div class="mask"> 
            <img src="{% static 'Images/pc.jpg' %}"> 
            <h1>The mask</h1> <h2>very important out door</h2> 
            <h3>use all day</h3>
            </div> </section> <footer id="foot">
        <div class="information"> <div class="icon"> 
            <img src="{% static 'Images/facebook.png' %}"> <img src="{% static 'Images/instagram.png' %}">
            <img src="{% static 'Images/youtube.png' %}"> </div> <div class="title2"> 
            <h3>&copy;2021 All Rights Reserved. </h3> 
    </div> 
    </div>
    </footer> </body> </html>